#!/usr/bin/perl -T

BEGIN {
    require "./debian/tests/utils/mock.pm";
    Cryptsetup::Mock::->import();
}

my %passphrases;
$passphrases{$_} = $_ foreach qw/root_crypt swap_crypt/;
unlock_disk(\%passphrases) for 1 .. scalar(%passphrases);

# check that the above was done at initramfs stage
expect(ttyS0 => qr#\bRunning /scripts/init-bottom\s*\.\.\. #);

login_nopassword("root");

# make sure the root FS and swap are help by dm-crypt devices
assert_command(q{cryptsetup luksOpen --test-passphrase /dev/testvg/cryptroot <<<root_crypt});
assert_command(q{cryptsetup luksOpen --test-passphrase /dev/testvg/cryptswap <<<swap_crypt});
my $out = shell_command(q{lsblk -in -oNAME,TYPE,MOUNTPOINT /dev/vda3});
die unless $out =~ m#^[`|]-testvg-cryptswap\s+lvm\s*$#m;
die unless $out =~ m#^[| ] `-swap_crypt\s+crypt\s+\[SWAP\]\s*$#m;
die unless $out =~ m#^[`|]-testvg-cryptroot\s+lvm\s*$#m;
die unless $out =~ m#^[| ] `-root_crypt\s+crypt\s+/\s*$#m;

poweroff();
